steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/digital-library', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/digital-library']

images:
- 'gcr.io/$PROJECT_ID/digital-library'

options:
  logging: CLOUD_LOGGING_ONLY
